import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shoptron Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
